prod:
  image: vizzuality/rw_widget:1.0.0${STAGING}
  command: start
  ports:
    - '3020'
  links:
    - redis
  env_file: prod.env

  log_driver: 'gelf'
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}

redis:
  image: redis
  container_name: redis_rw_widget