#!/bin/bash

case "$1" in
    develop)
        type docker-compose >/dev/null 2>&1 || { echo >&2 "docker-compose is required but it's not installed. Aborting."; exit 1; }
        docker-compose -f docker-compose-develop.yml build &&
        docker-compose -f docker-compose-develop.yml up
        ;;
    test)
        type docker-compose >/dev/null 2>&1 || { echo >&2 "docker-compose is required but it's not installed.  Aborting."; exit 1; }
        docker-compose -f docker-compose-test.yml run test
        ;;
    db)
        type docker-compose >/dev/null 2>&1 || { echo >&2 "docker-compose is required but it's not installed.  Aborting."; exit 1; }
        docker-compose -f docker-compose-develop.yml run web rake db:create RAILS_ENV=development &&
        docker-compose -f docker-compose-develop.yml run web rake db:migrate RAILS_ENV=development &&
        docker-compose -f docker-compose-test.yml run test rake db:create RAILS_ENV=test &&
        docker-compose -f docker-compose-test.yml run test rake db:migrate RAILS_ENV=test
        ;;
    *)
        echo "Usage: service {develop|test|db}" >&2
        exit 1
        ;;
esac

exit 0
